### ISSUE TITLE
Output rank by match score not index

### ISSUE THREAD

**Issue by DanielCGL** [DeNederlandscheBank/name_matching#30]
I have a data set with a list of company name and its search string, and I want to enter a name, which will be using name_matching to match the search string and output the company name. When I enter apple, I should get apple inc. because I have apple as a search string of apple inc. But the results give me a bunch of things ranked by index, but I want to rank by match score since it's the only way my apple will match apple inc., is there any way that I could match and rank by match score instead of match_index?
<img width="508" alt="Screenshot #1" src="https://github.com/user-attachments/assets/87da369b-52b6-4a47-9386-2b214bec07ca">

**Comment by mnijhuis-dnb** [comment]
Generally it should return the results ordered by score, do you have the code that you used to generate these results?

**Comment by DanielCGL** [comment]
yes:
`#Import Data File Code Before
matcher = NameMatcher(number_of_matches=7, 
                      legal_suffixes=True, 
                      common_words=False, 
                      top_n=50, 
                      verbose=True)

matcher.set_distance_metrics(['ssk', 'discounted_levenshtein', 'fuzzy_wuzzy_partial_string'])


matcher.load_and_process_master_data(column='Company Name',
                                     df_matching_data=df_companies, 
                                     transform=True)

def preprocess(text):
    text = text.lower()
    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(f'[{re.escape(string.punctuation)}]', '', text)
    text = basename(text)
    common_words = ['inc', 'ltd', 'corp', 'llc', 'co', 'company']
    for word in common_words:
        text = re.sub(r'\b{}\b'.format(re.escape(word)), '', text)
    text = ' '.join(text.split())
    return text

user_input = input("Please enter the match name: ")
processed_input = preprocess(user_input)

df_temp = pd.DataFrame([{'Search String': processed_input}])


matches = matcher.match_names(to_be_matched=df_temp, 
                              column_matching='Search String')


print("Matches DataFrame structure:")
print(matches)


if not matches.empty:
    for index, row in matches.iterrows():
        if 'match_index' in row and 'matching_score' in row:
            match_index = row['match_index']
            company_name = df_companies.iloc[match_index]['Company Name']
            score = row['matching_score']
            print(f"Match Company Name: {company_name}, Match Score: {score}")
        else:
            print(f"Row missing expected columns: {row}")
else:
    print("No Matches Found")`

**Comment by mnijhuis-dnb** [comment]
Thanks for the code, I found the place where the order got messed up, in the latest version it should be fixed
