### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\w' in run_nm.py on Python 3.12

### ISSUE THREAD

**Issue by lvhsuperuser** [DeNederlandscheBank/name_matching#31]
### Description:
While running the `name_matching` package on Python 3.12, a `SyntaxWarning` is encountered due to the use of an invalid escape sequence `\w` in the `run_nm.py` file. This warning is likely triggered by stricter escape sequence handling in newer Python versions.

#### Warning Message:
```
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/name_matching/run_nm.py:87
  /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/name_matching/run_nm.py:87: SyntaxWarning: invalid escape sequence '\w'
    data_first[column] = data_first[column].str.replace("[^\w\s]", "", regex=True)
```

### Affected File:
- **File:** `name_matching/run_nm.py`
- **Line:** 87

### Steps to Reproduce:
1. Install the `name_matching` package on a Python 3.12 environment.
2. Run the code that triggers the `run_nm.py` script.
3. Observe the `SyntaxWarning` in the output.

### Root Cause:
The warning is caused by the use of escape sequences within a normal string literal. Python interprets backslashes in strings as the beginning of an escape sequence. In this case, `\w` and `\s` are intended to be part of a regular expression, but Python issues a `SyntaxWarning` because the string isn't marked as a raw string.

### Proposed Solution:
To fix this issue, the regular expression string should be converted to a raw string by prefixing it with `r`. This will ensure that the backslashes are treated literally and passed correctly to the regular expression engine.

#### Suggested Code Change:
In the file `run_nm.py`, on line 87, change the following:

```python
data_first[column] = data_first[column].str.replace("[^\w\s]", "", regex=True)
```

To:

```python
data_first[column] = data_first[column].str.replace(r"[^\w\s]", "", regex=True)
```

### Rationale:
Using a raw string (`r""`) will prevent Python from interpreting `\w` and `\s` as escape sequences, thereby eliminating the `SyntaxWarning`. This change is backward compatible and ensures that the regular expression functions as intended.

### Impact:
- **Compatibility:** The fix will make the package compatible with Python 3.12 and future Python versions.
- **No Breaking Changes:** This change does not introduce any breaking changes and should not affect the package's functionality.

### Environment:
- **Python Version:** 3.12.4
- **name_matching Version:** 0.8.11

### Additional Notes:
If the package supports Python 3.12, this fix is necessary to avoid warnings and potential future errors as Python versions evolve.

**Comment by mnijhuis-dnb** [comment]
Thanks for info! This is now fixed in the latest version

**Comment by lvhsuperuser** [comment]
No problem at all, thanks for the quick response!
