### ISSUE TITLE
Incompatible with anaconda

### ISSUE THREAD

**Issue by u13e12** [DeNederlandscheBank/name_matching#7]
Currently Anaconda is on Python 3.9, which in PyPi it is listed that it Requires: Python <3.9

**Comment by mnijhuis-dnb** [comment]
It is because of the dependency on the abydos package that does not support Python version higher then 3.8, should be fixed in a future version

**Comment by mnijhuis-dnb** [comment]
Now the code is compatible with Python 3.10
