### ISSUE TITLE
Distance Metrics

### ISSUE THREAD

**Issue by philkim72** [DeNederlandscheBank/name_matching#8]
It seems the names of the distance metrics options have changed.  Where can I find the list of options and descriptions of each?

I get an error using this piece of code:

matcher.set_distance_metrics(['discounted_levenshtein', 'SSK', 'fuzzy_wuzzy_token_sort'])

However, this piece of code found in one of the sample notebooks works:

matcher.set_distance_metrics(['iterative_sub_string', 'pearson_ii', 'bag', 'fuzzy_wuzzy_partial_string', 'editex'])

**Comment by mnijhuis-dnb** [comment]
The list of the options was in the distance_metrics file, it has now also been added to the docstring of the set_distance_metrics method. The distance metric names are now no longer case sensitive, fixing the error you got
